version: "3.8"

services:
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        ports:
            - "8000:8000"
        volumes:
            - ./backend:/app
        env_file:
            - .env
        environment:
            # These values override the ones in .env, so we need to specify them
            - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/macro_finance
            - REDIS_URL=redis://redis:6379
            - FIREBASE_PROJECT_ID=${NEXT_PUBLIC_FIREBASE_PROJECT_ID}
            - FIREBASE_SERVICE_ACCOUNT_JSON=${FIREBASE_SERVICE_ACCOUNT_JSON}
        depends_on:
            - db
            - redis
        networks:
            - macro-finance-network

    db:
        image: postgres:15-alpine
        environment:
            - POSTGRES_DB=macro_finance
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
            - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
        networks:
            - macro-finance-network

    redis:
        image: redis:7-alpine
        ports:
            - "6379:6379"
        volumes:
            - redis_data:/data
        networks:
            - macro-finance-network

    # Frontend service (placeholder for future)
    # frontend:
    #   build:
    #     context: ./frontend
    #     dockerfile: Dockerfile
    #   ports:
    #     - "3000:3000"
    #   volumes:
    #     - ./frontend:/app
    #     - /app/node_modules
    #   environment:
    #     - REACT_APP_API_URL=http://localhost:8000
    #   depends_on:
    #     - backend
    #   networks:
    #     - macro-finance-network

volumes:
    postgres_data:
    redis_data:

networks:
    macro-finance-network:
        driver: bridge
