"""Add name column to users table

Revision ID: bad8ddc3505a
Revises: 
Create Date: 2025-06-12 12:45:55.467085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bad8ddc3505a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'portfolios', 'users', ['user_id'], ['uid'])
    op.add_column('users', sa.Column('name', sa.String(length=100), nullable=True, comment='사용자 이름'))
    op.drop_column('users', 'photo_url')
    op.drop_column('users', 'display_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('display_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True, comment='표시 이름'))
    op.add_column('users', sa.Column('photo_url', sa.VARCHAR(length=512), autoincrement=False, nullable=True, comment='프로필 사진 URL'))
    op.drop_column('users', 'name')
    op.drop_constraint(None, 'portfolios', type_='foreignkey')
    # ### end Alembic commands ###
